[project]
name = "sign-language"
version = "0.1.0"
description = "A project to detect American Sign Language."
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "joblib>=1.5.2",
    "mediapipe>=0.10.14",
    "opencv-python>=4.12.0.88",
    "scikit-learn>=1.7.2",
]
